export const config = {
    NODE_ENV: process.env.NODE_ENV,
    PORT: process.env.PORT,
    END_POINT_HOME: process.env.END_POINT_HOME,
    DATABASE: process.env.DATABASE,
    END_POINT_VIDEOS_PATH: process.env.END_POINT_VIDEOS_PATH,
    END_POINT_IMAGES_PATH: process.env.END_POINT_IMAGES_PATH,
    END_POINT_SERVER: process.env.END_POINT_SERVER,
    FB_ID: process.env.FB_ID,
    FB_KEY: process.env.FB_KEY,
    GG_ID: process.env.GG_ID,
    GG_KEY: process.env.GG_KEY,
    STATUS_REMOVE_LOCAL: process.env.STATUS_REMOVE_LOCAL,
    STATUS_REMOVE_AWS: process.env.STATUS_REMOVE_AWS,
    MAX_REQUEST: process.env.MAX_REQUEST,
    LIMIT_REQUEST: process.env.LIMIT_REQUEST,
    LIMIT_TIMER: process.env.LIMIT_TIMER,
    AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
    AWS_ACCESS: process.env.AWS_ACCESS,
    AWS_SECRET: process.env.AWS_SECRET,
    AWS_REGION: process.env.AWS_REGION,
    AWS_DOMAIN: process.env.AWS_DOMAIN,
    REDIS_URL: process.env.REDIS_URL,
}